import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Nagendra
 */
public class ConductExamFrame extends javax.swing.JFrame implements ActionListener {

    String subject;
    String level;
    int numberOfQuestions;
    int duration;
    int time;
    Exam exam;
    int currentIndex = 0;

    /** Creates new form ConductExamFrame */
    public ConductExamFrame(String subject, String level, int numberOfQuestions, int duration) {
        initComponents();
        this.subject = subject;
        this.level = level;
        this.numberOfQuestions = numberOfQuestions;
        this.duration = duration;
        time = duration * 60;
        exam = new Exam(subject, level, numberOfQuestions);
        tr = new Timer(1000, this);
    }

    public void actionPerformed(ActionEvent ae) {
        if (time >= 1) {
            time--;
        }
        updateLabel();
        if (time == 0) {
            tr.stop();
            JOptionPane.showMessageDialog(this, "Time Over\nYour Exam will now Finish");
            finishExam();
        }
    }

    private void updateLabel() {
        lblTimeRemaining.setText("Time Remaining : " + time / 60 + " Minutes " + time % 60 + " Seconds");
    }

    private void finishExam() {
        
        updateAnswer();
        ExamReport report = new ExamReport();
        report.setStudentName(System.getProperty("userName"));
        DateFormat fmt = new SimpleDateFormat("dd/MMMMM/yyyy");
        report.setExamDate(fmt.format(new java.util.Date()));
        report.setSubject(subject);
        report.setLevel(level);
        report.setNumberOfQuestions(numberOfQuestions);
        report.setAttempted(exam.getAttemptedQuestions());
        report.setCorrect(exam.getCorrectQuestions());
        DBManager.saveReport(report);
        ReportFrame f = new ReportFrame(report);
        f.setLocationRelativeTo(null);
        f.setParentFrame(parent);
        f.setVisible(true);
        ((MainFrame) parent).setChild(f);
        dispose();
    }

    private void updateAnswer() {
        Question q = exam.getQuestion(currentIndex);
        if (rboOptionA.isSelected()) {
            q.setUserAnswer("A");
        }
        if (rboOptionB.isSelected()) {
            q.setUserAnswer("B");
        }
        if (rboOptionC.isSelected()) {
            q.setUserAnswer("C");
        }
        if (rboOptionD.isSelected()) {
            q.setUserAnswer("D");
        }
    }

    private void setQuestion() {
        lblQNo.setText("Q.No. " + (currentIndex + 1) + " : ");
        Question q = exam.getQuestion(currentIndex);
        txtQuestionText.setText(q.getQuestionText());
        rboOptionA.setText(q.getOptionA());
        rboOptionB.setText(q.getOptionB());
        rboOptionC.setText(q.getOptionC());
        rboOptionD.setText(q.getOptionD());
        if (q.getUserAnswer().equals("")) {
            grpOption.clearSelection();
        } else {
            if (q.getUserAnswer().equals("A")) {
                rboOptionA.setSelected(true);
            } else if (q.getUserAnswer().equals("B")) {
                rboOptionB.setSelected(true);
            } else if (q.getUserAnswer().equals("C")) {
                rboOptionC.setSelected(true);
            } else if (q.getUserAnswer().equals("D")) {
                rboOptionD.setSelected(true);
            }
        }

        if (currentIndex == 0) {
            btnPrevious.setEnabled(false);
        } else {
            btnPrevious.setEnabled(true);
        }
        if (currentIndex == numberOfQuestions - 1) {
            btnNext.setEnabled(false);
        } else {
            btnNext.setEnabled(true);
        }
    }

    public void setParentFrame(JFrame f) {
        parent = f;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpOption = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSubject = new javax.swing.JLabel();
        lblNumberOfQuestions = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblQNo = new javax.swing.JLabel();
        rboOptionA = new javax.swing.JRadioButton();
        rboOptionB = new javax.swing.JRadioButton();
        rboOptionC = new javax.swing.JRadioButton();
        rboOptionD = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestionText = new javax.swing.JTextArea();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        lblTimeRemaining = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubject.setText("jLabel1");
        lblSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNumberOfQuestions.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNumberOfQuestions.setText("jLabel2");

        lblDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDuration.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberOfQuestions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addComponent(lblDuration)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(lblSubject)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfQuestions)
                    .addComponent(lblDuration))
                .addContainerGap())
        );

        lblQNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQNo.setText("jLabel1");
        lblQNo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        grpOption.add(rboOptionA);

        grpOption.add(rboOptionB);

        grpOption.add(rboOptionC);

        grpOption.add(rboOptionD);

        txtQuestionText.setColumns(20);
        txtQuestionText.setRows(5);
        jScrollPane1.setViewportView(txtQuestionText);

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        lblTimeRemaining.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimeRemaining.setText("jLabel1");
        lblTimeRemaining.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(btnPrevious)
                .addGap(30, 30, 30)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(lblTimeRemaining)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblQNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rboOptionD)
                    .addComponent(rboOptionC)
                    .addComponent(rboOptionA)
                    .addComponent(rboOptionB)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTimeRemaining)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQNo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(rboOptionA)
                .addGap(18, 18, 18)
                .addComponent(rboOptionB)
                .addGap(18, 18, 18)
                .addComponent(rboOptionC)
                .addGap(18, 18, 18)
                .addComponent(rboOptionD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnFinish))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblSubject.setText("Subject : " + subject);
        lblNumberOfQuestions.setText("Number of Questions : " + numberOfQuestions);
        lblDuration.setText("Duration : " + duration + " Minutes");
        tr.start();
        setQuestion();
        updateLabel();
    }//GEN-LAST:event_formWindowOpened

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        updateAnswer();
        if (currentIndex >= 1) {
            currentIndex--;
            setQuestion();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        updateAnswer();
        if (currentIndex < numberOfQuestions - 1) {
            currentIndex++;
            setQuestion();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Do you really want to FINISH your exam", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            tr.stop();
            finishExam();
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new ConductExamFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup grpOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblNumberOfQuestions;
    private javax.swing.JLabel lblQNo;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTimeRemaining;
    private javax.swing.JRadioButton rboOptionA;
    private javax.swing.JRadioButton rboOptionB;
    private javax.swing.JRadioButton rboOptionC;
    private javax.swing.JRadioButton rboOptionD;
    private javax.swing.JTextArea txtQuestionText;
    // End of variables declaration//GEN-END:variables
    private JFrame parent;
    private Timer tr;
}
